# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import jamf
from jamf.api.tomcat_settings_preview_api import TomcatSettingsPreviewApi  # noqa: E501
from jamf.rest import ApiException


class TestTomcatSettingsPreviewApi(unittest.TestCase):
    """TomcatSettingsPreviewApi unit test stubs"""

    def setUp(self):
        self.api = jamf.api.tomcat_settings_preview_api.TomcatSettingsPreviewApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_settings_issue_tomcat_ssl_certificate_post(self):
        """Test case for settings_issue_tomcat_ssl_certificate_post

        Generate a SSL Certificate using Jamf Certificate Authority   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
