# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import jamf
from jamf.api.smart_user_groups_preview_api import SmartUserGroupsPreviewApi  # noqa: E501
from jamf.rest import ApiException


class TestSmartUserGroupsPreviewApi(unittest.TestCase):
    """SmartUserGroupsPreviewApi unit test stubs"""

    def setUp(self):
        self.api = jamf.api.smart_user_groups_preview_api.SmartUserGroupsPreviewApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_smart_user_groups_id_recalculate_post(self):
        """Test case for v1_smart_user_groups_id_recalculate_post

        Recalculate the smart group for the given id and then return the ids for the users in the smart group   # noqa: E501
        """
        pass

    def test_v1_users_id_recalculate_smart_groups_post(self):
        """Test case for v1_users_id_recalculate_smart_groups_post

        Recalculate a smart group for the given user id and then return the count of smart groups the user falls into   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
