# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import jamf
from jamf.api.patches_api import PatchesApi  # noqa: E501
from jamf.rest import ApiException


class TestPatchesApi(unittest.TestCase):
    """PatchesApi unit test stubs"""

    def setUp(self):
        self.api = jamf.api.patches_api.PatchesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_patch_id_get(self):
        """Test case for patch_id_get

        Return Active Patch Summary   # noqa: E501
        """
        pass

    def test_patch_id_put(self):
        """Test case for patch_id_put

        Update patch report   # noqa: E501
        """
        pass

    def test_patch_id_versions_get(self):
        """Test case for patch_id_versions_get

        Return patch versions   # noqa: E501
        """
        pass

    def test_patch_obj_policy_id_get(self):
        """Test case for patch_obj_policy_id_get

        Return Patch Policy Summary   # noqa: E501
        """
        pass

    def test_patch_svc_disclaimer_agree_post(self):
        """Test case for patch_svc_disclaimer_agree_post

        Accept Patch reporting disclaimer   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
