# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import jamf
from jamf.api.cloud_ldap_api import CloudLdapApi  # noqa: E501
from jamf.rest import ApiException


class TestCloudLdapApi(unittest.TestCase):
    """CloudLdapApi unit test stubs"""

    def setUp(self):
        self.api = jamf.api.cloud_ldap_api.CloudLdapApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_cloud_ldaps_defaults_mappings_get(self):
        """Test case for v1_cloud_ldaps_defaults_mappings_get

        Get default mappings  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_defaults_server_configuration_get(self):
        """Test case for v1_cloud_ldaps_defaults_server_configuration_get

        Get default server configuration  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_get(self):
        """Test case for v1_cloud_ldaps_get

        Get all Cloud Identity Providers configurations.  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_connection_bind_get(self):
        """Test case for v1_cloud_ldaps_id_connection_bind_get

        Get bind connection pool statistics  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_connection_search_get(self):
        """Test case for v1_cloud_ldaps_id_connection_search_get

        Get search connection pool statistics  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_delete(self):
        """Test case for v1_cloud_ldaps_id_delete

        Delete Cloud Identity Provider configuration.  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_get(self):
        """Test case for v1_cloud_ldaps_id_get

        Get Cloud Identity Provider configuration with given id.  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_history_get(self):
        """Test case for v1_cloud_ldaps_id_history_get

        Get Cloud Identity Provider history  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_history_post(self):
        """Test case for v1_cloud_ldaps_id_history_post

        Add Cloud Identity Provider history note  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_mappings_get(self):
        """Test case for v1_cloud_ldaps_id_mappings_get

        Get mappings configurations for Cloud Identity Providers server configuration.  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_mappings_put(self):
        """Test case for v1_cloud_ldaps_id_mappings_put

        Update Cloud Identity Provider mappings configuration.  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_put(self):
        """Test case for v1_cloud_ldaps_id_put

        Update Cloud Identity Provider configuration  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_test_group_post(self):
        """Test case for v1_cloud_ldaps_id_test_group_post

        Get group test search  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_test_user_membership_post(self):
        """Test case for v1_cloud_ldaps_id_test_user_membership_post

        Get membership test search  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_id_test_user_post(self):
        """Test case for v1_cloud_ldaps_id_test_user_post

        Get user test search  # noqa: E501
        """
        pass

    def test_v1_cloud_ldaps_post(self):
        """Test case for v1_cloud_ldaps_post

        Create Cloud Identity Provider configuration  # noqa: E501
        """
        pass

    def test_v1_ldap_keystore_verify_post(self):
        """Test case for v1_ldap_keystore_verify_post

        Validate keystore for Cloud Identity Provider secure connection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
