# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import jamf
from jamf.models.search_patch_policy_log_params import SearchPatchPolicyLogParams  # noqa: E501
from jamf.rest import ApiException

class TestSearchPatchPolicyLogParams(unittest.TestCase):
    """SearchPatchPolicyLogParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SearchPatchPolicyLogParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = jamf.models.search_patch_policy_log_params.SearchPatchPolicyLogParams()  # noqa: E501
        if include_optional :
            return SearchPatchPolicyLogParams(
                page_number = 1, 
                page_size = 100, 
                order_by = [
                    jamf.models.order_by.OrderBy(
                        field = 'Name', 
                        direction = 'DESC', )
                    ], 
                filter = [
                    jamf.models.filter.Filter(
                        field = 'name', 
                        operator = 'EQUALS', 
                        value = 'value', )
                    ], 
                is_load_to_end = False, 
                patch_policy_id = 1, 
                is_latest = True
            )
        else :
            return SearchPatchPolicyLogParams(
        )

    def testSearchPatchPolicyLogParams(self):
        """Test SearchPatchPolicyLogParams"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
