# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import jamf
from jamf.api.departments_api import DepartmentsApi  # noqa: E501
from jamf.rest import ApiException


class TestDepartmentsApi(unittest.TestCase):
    """DepartmentsApi unit test stubs"""

    def setUp(self):
        self.api = jamf.api.departments_api.DepartmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_departments_delete_multiple_post(self):
        """Test case for v1_departments_delete_multiple_post

        Deletes all departments by ids passed in body   # noqa: E501
        """
        pass

    def test_v1_departments_get(self):
        """Test case for v1_departments_get

        Search for Departments   # noqa: E501
        """
        pass

    def test_v1_departments_id_delete(self):
        """Test case for v1_departments_id_delete

        Remove specified department record   # noqa: E501
        """
        pass

    def test_v1_departments_id_get(self):
        """Test case for v1_departments_id_get

        Get specified Department object   # noqa: E501
        """
        pass

    def test_v1_departments_id_history_get(self):
        """Test case for v1_departments_id_history_get

        Get specified Department history object   # noqa: E501
        """
        pass

    def test_v1_departments_id_history_post(self):
        """Test case for v1_departments_id_history_post

        Add specified Department history object notes   # noqa: E501
        """
        pass

    def test_v1_departments_id_put(self):
        """Test case for v1_departments_id_put

        Update specified department object   # noqa: E501
        """
        pass

    def test_v1_departments_post(self):
        """Test case for v1_departments_post

        Create department record   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
