# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.advanced_mobile_device_searches_api import AdvancedMobileDeviceSearchesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestAdvancedMobileDeviceSearchesApi(unittest.TestCase):
    """AdvancedMobileDeviceSearchesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.advanced_mobile_device_searches_api.AdvancedMobileDeviceSearchesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_advanced_mobile_device_searches_choices_get(self):
        """Test case for v1_advanced_mobile_device_searches_choices_get

        Get Mobile Device Advanced Search criteria choices   # noqa: E501
        """
        pass

    def test_v1_advanced_mobile_device_searches_delete_multiple_post(self):
        """Test case for v1_advanced_mobile_device_searches_delete_multiple_post

        Remove specified Advanced Search objects   # noqa: E501
        """
        pass

    def test_v1_advanced_mobile_device_searches_get(self):
        """Test case for v1_advanced_mobile_device_searches_get

        Get Advanced Search objects   # noqa: E501
        """
        pass

    def test_v1_advanced_mobile_device_searches_id_delete(self):
        """Test case for v1_advanced_mobile_device_searches_id_delete

        Remove specified Advanced Search object   # noqa: E501
        """
        pass

    def test_v1_advanced_mobile_device_searches_id_get(self):
        """Test case for v1_advanced_mobile_device_searches_id_get

        Get specified Advanced Search object   # noqa: E501
        """
        pass

    def test_v1_advanced_mobile_device_searches_id_put(self):
        """Test case for v1_advanced_mobile_device_searches_id_put

        Get specified Advanced Search object   # noqa: E501
        """
        pass

    def test_v1_advanced_mobile_device_searches_post(self):
        """Test case for v1_advanced_mobile_device_searches_post

        Create Advanced Search object   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
