# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.enrollment_settings import EnrollmentSettings  # noqa: E501
from openapi_client.rest import ApiException

class TestEnrollmentSettings(unittest.TestCase):
    """EnrollmentSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EnrollmentSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.enrollment_settings.EnrollmentSettings()  # noqa: E501
        if include_optional :
            return EnrollmentSettings(
                is_install_single_profile = True, 
                is_signing_mdm_profile_enabled = True, 
                mdm_signing_certificate = openapi_client.models.mdm_signing_certificate.MDMSigningCertificate(
                    filename = '0', 
                    keystore_password = '0', 
                    identity_keystore = '0', 
                    md5_sum = '0', ), 
                is_restrict_reenrollment = True, 
                is_flush_location_information = True, 
                is_flush_location_history_information = True, 
                is_flush_policy_history = True, 
                is_flush_extension_attributes = True, 
                flush_mdm_commands_on_reenroll = 'DELETE_EVERYTHING_EXCEPT_ACKNOWLEDGED', 
                is_enabled_macos_enterprise_enrollment = True, 
                management_username = '0', 
                management_password = '0', 
                password_type = 'STATIC', 
                random_password_length = 56, 
                is_create_management_account = True, 
                is_hide_management_account = True, 
                is_allow_ssh_only_management_account = True, 
                is_ensure_ssh_running = True, 
                is_launch_self_service = True, 
                is_sign_quick_add = True, 
                developer_certificate_identity = openapi_client.models.enrollment_settings_developer_certificate_identity.EnrollmentSettings_developerCertificateIdentity(
                    filename = '0', 
                    keystore_password = '0', 
                    identity_keystore = '0', 
                    md5_sum = '0', ), 
                developer_certificate_identity_details = openapi_client.models.certificate_details.CertificateDetails(
                    subject = '0', 
                    serial_number = '0', ), 
                mdm_signing_certificate_details = openapi_client.models.certificate_details.CertificateDetails(
                    subject = '0', 
                    serial_number = '0', ), 
                is_enable_ios_enterprise_enrollment = True, 
                is_enable_ios_personal_enrollment = True, 
                personal_device_enrollment_type = 'PERSONALDEVICEPROFILES'
            )
        else :
            return EnrollmentSettings(
        )

    def testEnrollmentSettings(self):
        """Test EnrollmentSettings"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
