# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.cache_settings import CacheSettings  # noqa: E501
from openapi_client.rest import ApiException

class TestCacheSettings(unittest.TestCase):
    """CacheSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CacheSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.cache_settings.CacheSettings()  # noqa: E501
        if include_optional :
            return CacheSettings(
                id = '0', 
                name = 'cache configuration', 
                cache_type = 'ehcache', 
                time_to_live_seconds = 120, 
                time_to_idle_seconds = 120, 
                ehcache_max_bytes_local_heap = '0', 
                cache_unique_id = '24864549-94ea-4cc1-bb80-d7fb392c6556', 
                elasticache = True, 
                memcached_endpoints = []
            )
        else :
            return CacheSettings(
                cache_type = 'ehcache',
                time_to_live_seconds = 120,
                cache_unique_id = '24864549-94ea-4cc1-bb80-d7fb392c6556',
                memcached_endpoints = [],
        )

    def testCacheSettings(self):
        """Test CacheSettings"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
