# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.teacher_app_api import TeacherAppApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTeacherAppApi(unittest.TestCase):
    """TeacherAppApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.teacher_app_api.TeacherAppApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_teacher_app_get(self):
        """Test case for v1_teacher_app_get

        Get the Jamf Teacher settings that you have access to see   # noqa: E501
        """
        pass

    def test_v1_teacher_app_history_get(self):
        """Test case for v1_teacher_app_history_get

        Get Jamf Teacher app settings history   # noqa: E501
        """
        pass

    def test_v1_teacher_app_history_post(self):
        """Test case for v1_teacher_app_history_post

        Add Jamf Teacher app settings history notes   # noqa: E501
        """
        pass

    def test_v1_teacher_app_put(self):
        """Test case for v1_teacher_app_put

        Update a Jamf Teacher settings object   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
