# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.sso_settings import SsoSettings  # noqa: E501
from openapi_client.rest import ApiException

class TestSsoSettings(unittest.TestCase):
    """SsoSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SsoSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.sso_settings.SsoSettings()  # noqa: E501
        if include_optional :
            return SsoSettings(
                sso_for_enrollment_enabled = True, 
                sso_bypass_allowed = True, 
                sso_enabled = True, 
                sso_for_mac_os_self_service_enabled = True, 
                token_expiration_disabled = True, 
                user_attribute_enabled = True, 
                user_attribute_name = '0', 
                user_mapping = 'USERNAME', 
                group_enrollment_access_enabled = True, 
                group_attribute_name = 'http://schemas.xmlsoap.org/claims/Group', 
                group_rdn_key = '0', 
                group_enrollment_access_name = '0', 
                idp_provider_type = 'ADFS', 
                idp_url = 'https://dev-940210.oktapreview.com/app/exk6bnecb9a4Z5spn0h7/sso/saml/metadata', 
                entity_id = 'saml/metadata', 
                metadata_file_name = 'if MetadataSource is set to URL, remove this field', 
                other_provider_type_name = '0', 
                federation_metadata_file = 'YQ==', 
                metadata_source = 'URL', 
                session_timeout = 56
            )
        else :
            return SsoSettings(
                sso_for_enrollment_enabled = True,
                sso_bypass_allowed = True,
                sso_enabled = True,
                sso_for_mac_os_self_service_enabled = True,
                token_expiration_disabled = True,
                user_attribute_enabled = True,
                user_mapping = 'USERNAME',
                group_enrollment_access_enabled = True,
                group_attribute_name = 'http://schemas.xmlsoap.org/claims/Group',
                group_rdn_key = '0',
                idp_provider_type = 'ADFS',
                entity_id = 'saml/metadata',
                metadata_source = 'URL',
        )

    def testSsoSettings(self):
        """Test SsoSettings"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
