# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.supervision_identities_preview_api import SupervisionIdentitiesPreviewApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSupervisionIdentitiesPreviewApi(unittest.TestCase):
    """SupervisionIdentitiesPreviewApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.supervision_identities_preview_api.SupervisionIdentitiesPreviewApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_supervision_identities_get(self):
        """Test case for v1_supervision_identities_get

        Search for sorted and paged Supervision Identities   # noqa: E501
        """
        pass

    def test_v1_supervision_identities_id_delete(self):
        """Test case for v1_supervision_identities_id_delete

        Delete a Supervision Identity with the supplied id   # noqa: E501
        """
        pass

    def test_v1_supervision_identities_id_download_get(self):
        """Test case for v1_supervision_identities_id_download_get

        Download the Supervision Identity .p12 file   # noqa: E501
        """
        pass

    def test_v1_supervision_identities_id_get(self):
        """Test case for v1_supervision_identities_id_get

        Retrieve a Supervision Identity with the supplied id   # noqa: E501
        """
        pass

    def test_v1_supervision_identities_id_put(self):
        """Test case for v1_supervision_identities_id_put

        Update a Supervision Identity with the supplied information   # noqa: E501
        """
        pass

    def test_v1_supervision_identities_post(self):
        """Test case for v1_supervision_identities_post

        Create a Supervision Identity for the supplied information   # noqa: E501
        """
        pass

    def test_v1_supervision_identities_upload_post(self):
        """Test case for v1_supervision_identities_upload_post

        Upload the Supervision Identity .p12 file   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
