# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import jamf
from jamf.api.buildings_api import BuildingsApi  # noqa: E501
from jamf.rest import ApiException


class TestBuildingsApi(unittest.TestCase):
    """BuildingsApi unit test stubs"""

    def setUp(self):
        self.api = jamf.api.buildings_api.BuildingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_buildings_delete_multiple_post(self):
        """Test case for v1_buildings_delete_multiple_post

        Delete multiple Buildings by their ids   # noqa: E501
        """
        pass

    def test_v1_buildings_get(self):
        """Test case for v1_buildings_get

        Search for sorted and paged Buildings   # noqa: E501
        """
        pass

    def test_v1_buildings_id_delete(self):
        """Test case for v1_buildings_id_delete

        Remove specified Building record   # noqa: E501
        """
        pass

    def test_v1_buildings_id_get(self):
        """Test case for v1_buildings_id_get

        Get specified Building object   # noqa: E501
        """
        pass

    def test_v1_buildings_id_history_get(self):
        """Test case for v1_buildings_id_history_get

        Get specified Building History object   # noqa: E501
        """
        pass

    def test_v1_buildings_id_history_post(self):
        """Test case for v1_buildings_id_history_post

        Add specified Building history object notes   # noqa: E501
        """
        pass

    def test_v1_buildings_id_put(self):
        """Test case for v1_buildings_id_put

        Update specified Building object   # noqa: E501
        """
        pass

    def test_v1_buildings_post(self):
        """Test case for v1_buildings_post

        Create Building record   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
