# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from jamf.configuration import Configuration


class ComputerStorage(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'boot_drive_available_space_megabytes': 'int',
        'disks': 'list[ComputerDisk]'
    }

    attribute_map = {
        'boot_drive_available_space_megabytes': 'bootDriveAvailableSpaceMegabytes',
        'disks': 'disks'
    }

    def __init__(self, boot_drive_available_space_megabytes=None, disks=None, local_vars_configuration=None):  # noqa: E501
        """ComputerStorage - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._boot_drive_available_space_megabytes = None
        self._disks = None
        self.discriminator = None

        if boot_drive_available_space_megabytes is not None:
            self.boot_drive_available_space_megabytes = boot_drive_available_space_megabytes
        if disks is not None:
            self.disks = disks

    @property
    def boot_drive_available_space_megabytes(self):
        """Gets the boot_drive_available_space_megabytes of this ComputerStorage.  # noqa: E501


        :return: The boot_drive_available_space_megabytes of this ComputerStorage.  # noqa: E501
        :rtype: int
        """
        return self._boot_drive_available_space_megabytes

    @boot_drive_available_space_megabytes.setter
    def boot_drive_available_space_megabytes(self, boot_drive_available_space_megabytes):
        """Sets the boot_drive_available_space_megabytes of this ComputerStorage.


        :param boot_drive_available_space_megabytes: The boot_drive_available_space_megabytes of this ComputerStorage.  # noqa: E501
        :type boot_drive_available_space_megabytes: int
        """

        self._boot_drive_available_space_megabytes = boot_drive_available_space_megabytes

    @property
    def disks(self):
        """Gets the disks of this ComputerStorage.  # noqa: E501


        :return: The disks of this ComputerStorage.  # noqa: E501
        :rtype: list[ComputerDisk]
        """
        return self._disks

    @disks.setter
    def disks(self, disks):
        """Sets the disks of this ComputerStorage.


        :param disks: The disks of this ComputerStorage.  # noqa: E501
        :type disks: list[ComputerDisk]
        """

        self._disks = disks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComputerStorage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ComputerStorage):
            return True

        return self.to_dict() != other.to_dict()
