# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from jamf.configuration import Configuration


class UpdateTvOs(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'airplay_password': 'str',
        'purchasing': 'PurchasingV2'
    }

    attribute_map = {
        'airplay_password': 'airplayPassword',
        'purchasing': 'purchasing'
    }

    def __init__(self, airplay_password=None, purchasing=None, local_vars_configuration=None):  # noqa: E501
        """UpdateTvOs - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._airplay_password = None
        self._purchasing = None
        self.discriminator = None

        if airplay_password is not None:
            self.airplay_password = airplay_password
        if purchasing is not None:
            self.purchasing = purchasing

    @property
    def airplay_password(self):
        """Gets the airplay_password of this UpdateTvOs.  # noqa: E501


        :return: The airplay_password of this UpdateTvOs.  # noqa: E501
        :rtype: str
        """
        return self._airplay_password

    @airplay_password.setter
    def airplay_password(self, airplay_password):
        """Sets the airplay_password of this UpdateTvOs.


        :param airplay_password: The airplay_password of this UpdateTvOs.  # noqa: E501
        :type airplay_password: str
        """

        self._airplay_password = airplay_password

    @property
    def purchasing(self):
        """Gets the purchasing of this UpdateTvOs.  # noqa: E501


        :return: The purchasing of this UpdateTvOs.  # noqa: E501
        :rtype: PurchasingV2
        """
        return self._purchasing

    @purchasing.setter
    def purchasing(self, purchasing):
        """Sets the purchasing of this UpdateTvOs.


        :param purchasing: The purchasing of this UpdateTvOs.  # noqa: E501
        :type purchasing: PurchasingV2
        """

        self._purchasing = purchasing

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateTvOs):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateTvOs):
            return True

        return self.to_dict() != other.to_dict()
