# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ComputerSection(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    GENERAL = "GENERAL"
    DISK_ENCRYPTION = "DISK_ENCRYPTION"
    PURCHASING = "PURCHASING"
    APPLICATIONS = "APPLICATIONS"
    STORAGE = "STORAGE"
    USER_AND_LOCATION = "USER_AND_LOCATION"
    CONFIGURATION_PROFILES = "CONFIGURATION_PROFILES"
    PRINTERS = "PRINTERS"
    SERVICES = "SERVICES"
    HARDWARE = "HARDWARE"
    LOCAL_USER_ACCOUNTS = "LOCAL_USER_ACCOUNTS"
    CERTIFICATES = "CERTIFICATES"
    ATTACHMENTS = "ATTACHMENTS"
    PLUGINS = "PLUGINS"
    PACKAGE_RECEIPTS = "PACKAGE_RECEIPTS"
    FONTS = "FONTS"
    SECURITY = "SECURITY"
    OPERATING_SYSTEM = "OPERATING_SYSTEM"
    LICENSED_SOFTWARE = "LICENSED_SOFTWARE"
    IBEACONS = "IBEACONS"
    SOFTWARE_UPDATES = "SOFTWARE_UPDATES"
    EXTENSION_ATTRIBUTES = "EXTENSION_ATTRIBUTES"
    CONTENT_CACHING = "CONTENT_CACHING"
    GROUP_MEMBERSHIPS = "GROUP_MEMBERSHIPS"

    allowable_values = [GENERAL, DISK_ENCRYPTION, PURCHASING, APPLICATIONS, STORAGE, USER_AND_LOCATION, CONFIGURATION_PROFILES, PRINTERS, SERVICES, HARDWARE, LOCAL_USER_ACCOUNTS, CERTIFICATES, ATTACHMENTS, PLUGINS, PACKAGE_RECEIPTS, FONTS, SECURITY, OPERATING_SYSTEM, LICENSED_SOFTWARE, IBEACONS, SOFTWARE_UPDATES, EXTENSION_ATTRIBUTES, CONTENT_CACHING, GROUP_MEMBERSHIPS]  # noqa: E501

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
    }

    attribute_map = {
    }

    def __init__(self, local_vars_configuration=None):  # noqa: E501
        """ComputerSection - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComputerSection):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ComputerSection):
            return True

        return self.to_dict() != other.to_dict()
