# coding: utf-8

"""
    Jamf Pro API

    ## Overview This is a sample Jamf Pro server which allows for usage without any authentication. The Jamf Pro environment which supports the Try it Out functionality does not run the current beta version of Jamf Pro, thus any newly added endpoints will result in an error and should be used soley for documentation purposes.   # noqa: E501

    The version of the OpenAPI document: 10.25.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ComputerContentCachingDataMigrationError(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'code': 'int',
        'domain': 'str',
        'user_info': 'list[ComputerContentCachingDataMigrationErrorUserInfo]'
    }

    attribute_map = {
        'code': 'code',
        'domain': 'domain',
        'user_info': 'userInfo'
    }

    def __init__(self, code=None, domain=None, user_info=None, local_vars_configuration=None):  # noqa: E501
        """ComputerContentCachingDataMigrationError - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._code = None
        self._domain = None
        self._user_info = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if domain is not None:
            self.domain = domain
        if user_info is not None:
            self.user_info = user_info

    @property
    def code(self):
        """Gets the code of this ComputerContentCachingDataMigrationError.  # noqa: E501


        :return: The code of this ComputerContentCachingDataMigrationError.  # noqa: E501
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ComputerContentCachingDataMigrationError.


        :param code: The code of this ComputerContentCachingDataMigrationError.  # noqa: E501
        :type code: int
        """

        self._code = code

    @property
    def domain(self):
        """Gets the domain of this ComputerContentCachingDataMigrationError.  # noqa: E501


        :return: The domain of this ComputerContentCachingDataMigrationError.  # noqa: E501
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this ComputerContentCachingDataMigrationError.


        :param domain: The domain of this ComputerContentCachingDataMigrationError.  # noqa: E501
        :type domain: str
        """

        self._domain = domain

    @property
    def user_info(self):
        """Gets the user_info of this ComputerContentCachingDataMigrationError.  # noqa: E501


        :return: The user_info of this ComputerContentCachingDataMigrationError.  # noqa: E501
        :rtype: list[ComputerContentCachingDataMigrationErrorUserInfo]
        """
        return self._user_info

    @user_info.setter
    def user_info(self, user_info):
        """Sets the user_info of this ComputerContentCachingDataMigrationError.


        :param user_info: The user_info of this ComputerContentCachingDataMigrationError.  # noqa: E501
        :type user_info: list[ComputerContentCachingDataMigrationErrorUserInfo]
        """

        self._user_info = user_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComputerContentCachingDataMigrationError):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ComputerContentCachingDataMigrationError):
            return True

        return self.to_dict() != other.to_dict()
